[package]
name = "ckks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnum = "0.11.0"
rand = "0.8"
rand_distr = "0.4"